# Branch Protection Configuration
# This file documents the branch protection rules to be set up in GitHub/GitLab

protection:
  # Main branch protection
  main:
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
    required_status_checks:
      strict: true
      contexts:
        - lint
        - build
    enforce_admins: true
    restrictions: null
    
  # Develop branch protection
  develop:
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
    required_status_checks:
      strict: true
      contexts:
        - lint
        - build
    enforce_admins: false
    restrictions: null